export { default as HomePage } from '~/pages/home/HomePage'
export { default as HospitalPage } from '~/pages/hospital/HospitalPage'
export { default as DoctorPage } from '~/pages/doctor/DoctorPage'
export { default as UserPage } from '~/pages/user/UserPage'
export { default as LoginPage } from '~/pages/login/LoginPage'
export { default as NewsPage } from '~/pages/news/NewsPage'
export { default as AboutPage } from '~/pages/about/AboutPage'
export { default as NotFoundPage } from '~/pages/not-found/NotFoundPage'
